name: reciever_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  battery_plus: ^5.0.2
  photo_view: ^0.14.0
  video_player: ^2.7.2
  just_audio: ^0.9.35
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_broadcasts: ^0.4.0

flutter:
  uses-material-design: true

  # ✅ Add your assets here
  assets:
    - assets/sample.mp3
    - assets/sample.mp4
    - assets/image.jpg 
    
